### ISSUE TITLE
Weekly Schedule

### ISSUE THREAD

**Issue by perezandy** [shovere/Telesnooze#4]
Andy has a very specific schedule and only needs to be woken up certain days of the week. He would prefer an option to select which days to enable phone calls.

Frontend:
Add a responsive user interface of 7 checkboxes per week, using angular material and sending it's state to the backend.

Backend:
Store a user's saved date selection to their account by adding a row to the database accommodating the aforementioned schedule.

**Comment by NotMagolor** [comment]
completed
